env:
  browser: true
  es2021: true
  node: true
  serviceworker: true
extends: 'eslint:recommended'
globals:
  chrome: readonly
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  comma-dangle:
    - error
    - always-multiline
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  no-unused-vars:
    - error
    - varsIgnorePattern: ^_
  object-curly-spacing:
    - error
    - never
  quotes:
    - error
    - single
  semi:
    - error
    - never
