env:
  browser: true
  es2021: true
  node: true
  jest: true
  serviceworker: true
extends: 'eslint:recommended'
globals:
  chrome: readonly
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
