name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: dcodeIO/setup-node-nvm@master
      with:
        node-version: lts/fermium
    - uses: microsoft/playwright-github-action@v1
    - run: npm ci
    - run: npm run build --if-present
    - run: xvfb-run --auto-servernum -- npm test
