name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - run: npx playwright install-deps chromium
    - run: npm install
    - run: npm run build --if-present
    - run: npm run lint
    - run: xvfb-run --auto-servernum -- npm test
