name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
    - run: npm run unit
    - run: npx playwright install-deps chromium
    - run: npm run build
    - run: xvfb-run --auto-servernum -- npm test
